### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by matheusclmb** [YaMaSei99/csgo-cheat#1]
Hey man, i want to test your program but i can't make it work. Whenever i run,  it doesn't show any error on terminal and says the cheats are active. I tried to change the keybinds and toggle it but none of my solutions worked. Could you try to see if it's your end or mine?
![BSHToAO](https://user-images.githubusercontent.com/83146584/168636822-31b23f08-1643-4f0f-a3df-8161883b4adf.jpg)

**Comment by YaMaSei99** [comment]
Hey man, thank you for trying it out!

You probably have wrong offsets in the addresses.py file. After every csgo update they change the offsets so that the offsets in addresses.py were not correct anymore and hence the cheat isnt working. Watch out for the csgo version (current version as of today is v1463) which should match with the addresses.py. If there is an update it might take me some time to update the addresses so please understand. You can also fix the addresses by yourself: [https://www.youtube.com/watch?v=x0aRYH5StZI](url)

This is how it should look like:

https://user-images.githubusercontent.com/85324641/171675222-f0773f61-5920-469f-9948-3ee1b649917a.mp4

Hope that explains it!
